import "@/styles/globals.css";
import { Inter } from "next/font/google";

import { ServerThemeProvider } from "next-themes";
import { Providers } from "../components/providers";
import Header01 from "@/components/ui/header/header01";
import Footer from "../components/ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  // header start
  let header;
  // if (
  //   route.asPath === "/home/home_3" ||
  //   route.asPath === "/home/home_9" ||
  //   route.asPath === "/maintenance" ||
  //   route.asPath === "/home/home_12"
  // ) {
  //   header = <Header02 />;
  // } else if (route.asPath === "/platform_status") {
  //   header = <Header03 />;
  // } else if (route.asPath === "/home/home_8") {
  //   header = <Header04 />;
  // } else {
  //   header = <Header01 />;
  // }
  // header end

  return (
    <ServerThemeProvider attribute="class">
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={inter.className}>
          <Header01 />
          <Providers>
            {/* {header} */}
            {children}
            <Footer />
          </Providers>
        </body>
      </html>
    </ServerThemeProvider>
  );
}
