-- CreateTable
CREATE TABLE "Collection" (
    "id" BIGSERIAL NOT NULL,
    "contract_address" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "description" TEXT,
    "website" TEXT,
    "email" TEXT,
    "twitter" TEXT,
    "discord" TEXT,
    "telegram" TEXT,
    "github" TEXT,
    "instagram" TEXT,
    "medium" TEXT,
    "logo_url" TEXT,
    "banner_url" TEXT,
    "featured_url" TEXT,
    "large_image_url" TEXT,
    "attributes" JSONB,
    "erc_type" TEXT NOT NULL,
    "token_type" TEXT NOT NULL,
    "deploy_block_number" BIGINT NOT NULL,
    "owner" TEXT NOT NULL,
    "contract_deployer" TEXT NOT NULL,
    "verified" BOOLEAN NOT NULL,
    "opensea_verified" BOOLEAN NOT NULL,
    "baddogs_verified" BOOLEAN NOT NULL,
    "rug_verified" BOOLEAN NOT NULL,
    "sus_verified" BOOLEAN NOT NULL,
    "royalty" DOUBLE PRECISION,
    "items_total" BIGINT NOT NULL,
    "amounts_total" BIGINT NOT NULL,
    "owners_total" INTEGER NOT NULL,
    "opensea_floor_price" DOUBLE PRECISION NOT NULL,
    "floor_price" DOUBLE PRECISION NOT NULL,
    "collections_with_same_name" JSONB,
    "price_symbol" TEXT NOT NULL,
    "volume_total" DOUBLE PRECISION,
    "sales_total" INTEGER,
    "average_price" DOUBLE PRECISION,
    "lowest_price_24h" DOUBLE PRECISION,
    "average_price_24h" DOUBLE PRECISION,
    "volume_24h" DOUBLE PRECISION,
    "sales_24h" INTEGER,
    "highest_price" DOUBLE PRECISION,
    "volume_1d" DOUBLE PRECISION,
    "volume_7d" DOUBLE PRECISION,
    "volume_30d" DOUBLE PRECISION,
    "volume_change_1d" TEXT,
    "volume_change_7d" TEXT,
    "volume_change_30d" TEXT,
    "market_cap" BIGINT,
    "average_price_change_1d" TEXT,
    "average_price_change_7d" TEXT,
    "average_price_change_30d" TEXT,
    "last_ingested_at" TIMESTAMP(3),
    "last_updated_at" TIMESTAMP(3),

    CONSTRAINT "Collection_pkey" PRIMARY KEY ("id")
);
